<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Penghou.Guihua.Zhinu\Penghou.Guihua.Zhinu.csproj" />
    <PackageReference Include="Penghou.Fuwen.Compiler" Version="0.1.0-preview.11" />
    <PackageReference Include="Penghou.Zhinu.Sqlite" Version="0.1.0-preview.14" />
    <PackageReference Include="coverlet.msbuild" Version="6.0.4" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" Version="1.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0-pre.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="FluentAssertions" Version="7.*" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
